name: Build and Deploy

on:
  push:
    branches:
      - main # Adjust this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build wasm
        run: wasm-pack build

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install npm dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        run: |
          npm run build # Adjust this to your project's build script
          npm run start
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout --orphan gh-pages
          git --set-upstream-to=origin/main gh-pages
          git add -A
          git commit -m "GitHub Pages build by ${{ github.actor }}"
          git push -f origin gh-pages
